#get all blogs
get http://localhost:3003/api/blogs
###
#create blog
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b3VyaW5nIiwiaWQiOiI1ZDk0YjExNGY1YzE2MDI4MGMxNmU0NjMiLCJpYXQiOjE1NzAwMjU3NTh9.r1CfhVjQ-wnutM4ut5I7sGPFLz7fI8Q5n95mQkqLgXU

{
  "title": "weatherstack: an Amazing Weather API",
  "author": "David Walsh",
  "url": "https://davidwalsh.name/weatherstack-an-amazing-weather-api",
  "likes": 99
}
###
#create blog
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b3VyaW5nIiwiaWQiOiI1ZDk0YTk0MjBlM2UzZDJmYjhlOWUwZjkiLCJpYXQiOjE1NzAwMjUxMDl9.BzxWWo5nCdpxnH6QFTpFK5HwQMzgmFSgNeQZgHNXxeA

{
  "title": "title1",
  "author": "Author1",
  "url": "https://google.com",
  "likes": 123
}
###
#delete blog
delete http://localhost:3003/api/blogs/5d94b12ff5c160280c16e465
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF0b3VyaW5nIiwiaWQiOiI1ZDk0YjExNGY1YzE2MDI4MGMxNmU0NjMiLCJpYXQiOjE1NzAwMjU4OTh9.owNHYbNwRO3iHqJVsqLNPFIwg3FSLUxzFjlXkXyRCXA
